server.port=8082
spring.config.import=file:./.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://Techa:q7jxUSYYY9swfjX5@cluster0.acae2ef.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DATABASE:smart-campus}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sliit.smart.system@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fuwn nfud ouik fsdw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true