server:
  port: 8082

spring:
  mongodb:
    uri: "mongodb+srv://lakvidusarada_db_user:Saradalak%401231ss@cluster0.vf2wa36.mongodb.net/smartcampus?retryWrites=true&w=majority"
  data:
    mongodb:
      uri: "mongodb+srv://lakvidusarada_db_user:Saradalak%401231ss@cluster0.vf2wa36.mongodb.net/smartcampus?retryWrites=true&w=majority"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
