server.port=8081
spring.config.import=file:./.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://palindapasindu_db_user:8wzcLoVH9shXXotZ@paf-development.s3evrzi.mongodb.net/smart_campus?authSource=admin}
spring.data.mongodb.database=${MONGODB_DATABASE:smart_campus}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sliit.smart.system@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fuwn nfud ouik fsdw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Seeder Passwords 
app.seed.admin.password=${ADMIN_PASSWORD:SuperAdmin123}
app.seed.technician.password=${TECHNICIAN_PASSWORD:Tech123}